baseURL = "/"
title = "Gem Leather"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[languages.en]
weight = 0
languageName = "English"

[languages.cn]
weight = 10
languageName = "中文"


[languages.cn.params]
fancyTitle = "Gem Leather" # title for frontpage, may include image
copyright = "天津金莱德新材料科技有限公司"
description = '环保生态皮革<br /><br /><strong style="font-size: 40px">创新专家</strong>'
startbuttonText = "立即咨询"
startbuttonLink = "#contact"
body_is_markdown = 'true'
#custom_css = "foo.css"

[languages.en.params]
fancyTitle = "Gem Leather" # title for frontpage, may include image
copyright = "TIANIN GEM LFATHER NEW MATERIAL TECHNOLOGY CO.,LTD"
description = 'ZERO SOLVENT<br><br><strong style="font-size: 40px">TPEE SYNTHETIC LEATHER</strong>'
startbuttonText = "consult"
startbuttonLink = "#contact"
body_is_markdown = 'true'


[[languages.cn.params.menu.main]]
url = '/'
title = "首页"
[[languages.en.params.menu.main]]
url = '/'
title = "home"

[[languages.cn.params.menu.main]]
url = '#one'
title = "产品应用领域"
[[languages.en.params.menu.main]]
url = '#one'
title = "product"

[[languages.cn.params.menu.main]]
url = '#three'
title = "关于我们"
[[languages.en.params.menu.main]]
url = '#three'
title = "about us"

[[languages.cn.params.menu.main]]
url = '#contact'
title = "联系我们"
[[languages.en.params.menu.main]]
url = '#contact'
title = "contact us"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[languages.cn.params.one]
enable = true
img = '/images/gather.png'
title = '产品应用领域'
body = '''
公司消化融合国内外先进技术，结合生产实践，特殊设计、研发、定制的先进高速自动化的涂复生产线，可高速挤出并直接复合成型，取代传统线下二次、三次复合的形式,过程中无废水、废气产生，全程绿色环保生产。
'''
[languages.en.params.one]
enable = true
img = '/images/gather.png'
title = 'APPLICATION FIELD'
body = '''
The company integrates domestic and foreign advanced technology, combined with
production practice, special design, research and development, and customized advanced
high- speed automatic coating production line. This allows for high-speed extrusion and
direct composite molding, instead of the traditional offline two, three times composite
form. There is no waste water and waste gas in the production process, leading to the whole
process of green production.
'''

[languages.cn.params.two]
enable = true
[languages.en.params.two]
enable = true

[[languages.cn.params.two.section]]
img = "/images/product1.png"
title = '家具面料'
body = '亲肤性优异、不使用溶剂、无甲醛、超低VOC释放、抗 水解、抗老化、易清洁可应用于室外，对环境友好且十分安全。'
[[languages.en.params.two.section]]
img = "/images/product1.png"
title = 'Furniture fabric'
body = 'With excellent skin-friendly properties, hydrolysis resistance, and aging resistance, our product is free of solvent and formaldehyde with ultra-low VOC release, and can be easily cleaned and used outdoors for its environmental friendliness and safety features.'

[[languages.cn.params.two.section]]
img = "/images/automotive-trim.jpg"
title = '汽车内饰'
body = '材料通体着色，无色牢度困扰，结合优异的阻燃性能、抗 水解性能，同时又具备零溶剂、零甲醛、零VOC、无异味的环保优势，是汽车内饰材料的不二之选。'
[[languages.en.params.two.section]]
img = "/images/automotive-trim.jpg"
title = 'Automotive trim'
body = 'The material is through-colored, without any defects in color fastness. With excellent flame retardancy and hydrolysis resistance, it is environment-friendly, free of any solvent, formaldehyde, VOC, and odor and is the best choice for automotive interior materials.'

[[languages.cn.params.two.section]]
img = "/images/yacht-decoration.jpg"
title = '游艇装饰'
body = '材料本身抗水解能力即可达十年之久，同时具有优异的 抗酸碱能力、抗腐蚀能力、抗UV能力、抗摩擦能力，可广泛应用于室外及恶劣气候环境中。'
[[languages.en.params.two.section]]
img = "/images/yacht-decoration.jpg"
title = 'Yacht decoration'
body = '''
The hydrolysis resistance of the material can last up to ten years. With excellent resistance to acid and alkali, corrosion, UV and friction, it can be extensively applied in outdoors and harsh weather environments.
'''

[[languages.cn.params.two.section]]
img = "/images/shoe-leather.jpg"
title = '鞋革鞋材'
body = '耐磨、耐低温、抗水解、无异味，多种纹路、多种色彩、多种选择，产品面细腻、严实、颜色均匀。'
[[languages.en.params.two.section]]
img = "/images/shoe-leather.jpg"
title = 'Shoe leather and material'
body = '''
It is wear-resistant, low-temperature resistant, hydrolysis resistant, and odor-free with multiple pattern and color choices available. The product grain is fine, compact, and uniform in color.
'''

[[languages.cn.params.two.section]]
img = "/images/upholstery.jpg"
title = '建筑软包'
body = '具有防撞、阻燃、环保、防水、易清洁的五大特性，无甲醛 释放、无异味、极低的VOC挥发、无重金属危害，可同时解決多重问题，减少重复施工，品质长期稳定。'
[[languages.en.params.two.section]]
img = "/images/upholstery.jpg"
title = 'Upholstery'
body = '''
Characterized by anti-collision, flame retardant, environment-friendly, waterproof, and easy to clean, our product is also free of formaldehyde, odor, and heavy metal hazards with extremely low VOC volatilization. It can address various problems at the same time, avoiding repeated construction and guaranteeing long-term quality.
'''

[[languages.cn.params.two.section]]
img = "/images/bag.jpg"
title = '箱包皮具'
body = '复合A级皮革标准，环保无异味、可塑性强、耐水解、仿真度高、耐磨不易破损、色泽明艳、质地纯正，可媲美大部分动物皮革，使奢修品大众化。'
[[languages.en.params.two.section]]
img = "/images/bag.jpg"
title = 'Bags & Accessories'
body = '''
Our product meets the A-grade leather standard, it is environment-friendly, odor-free, flexible, hydrolysis-resistant, highly simulated, wear-resistant, bright and lustrous, and pure in texture, and is comparable to most genuine animal leathers. We make luxury leather products accessible to every household.
'''

[[languages.cn.params.two.section]]
img = "/images/massage-chair.jpg"
title = '按摩椅'
body = '弹性佳、韧性强、亲肤性优异、耐酒精擦拭、耐汗渍腐蚀、耐摩擦开列、零甲醛、零异味'
[[languages.en.params.two.section]]
img = "/images/massage-chair.jpg"
title = 'Massage chair'
body = '''
With favorable elasticity, strong toughness, and excellent skin-friendly property, our product has strong resistance to alcohol, sweat corrosion, friction resistance, and cracking, and is free of formaldehyde and odor.
'''

[languages.cn.params.three]
enable = true
title = '关于我们'
body = '''
天津金莱德新材料科技有限公司，是一家经十余年的技术积累沉淀，专注于皮革环保新材料的研究、开发、应用及生产销售的高科技企业，主要的生产技术自主研发，生产工艺属于国内首创。公司及研发基地坐落于天津市西青区赛达工业园，并规划在福建投资建设20万平米的研发生产基地，致力于发展成为国内一流的环保生态皮革供应商。
'''
[languages.en.params.three]
enable = true
title = 'about us'
body_is_markdown = true
body = '''
Tianjin GEM Leather New Material Technology Co., Ltd. is a high-tech enterprise focusing on the research, development, application, production and sales of new leather environmental protection materials after more than ten years of technological accumulation. The main production technology is an independent research and development. This production process is the first one in China. The company and its R&D base are located in Saida Industrial Park, Xiging District, Tianjin. The company plans to invest and build a R&D and production base of 200,000 square meters in Fujian, and is committed to develop into a first-class environmental protection ecological leather supplier in China.

Company uses creative technology research and development of elastic leather environmental protection technology to overcome the composite process of material restrictions, which through the composite process produce 100% environ- mental protection products, leading to green production. ***100% recyclable, zero solvent, hydrolysis resistance for more than ten years, zero formaldehyde, zero VOC, minus 50 degrees cold resistance, high temperature resistance, no heavy metal residue, flame retardant, wear resistance, tear resistance.*** The elastomer environmentally friendly leather products developed can be used in construction, automobile, sofa, clothing, shoe materials, bags and other fields.
'''
[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[languages.cn.params.contact]
enable = false
title = "联系我们"
body = "请给我们留言"
phone1 = "136 9300 3803"
phone2 = "134 8882 8598"
address = "天津市西青区王稳庄镇盛达一支路40号-11号"
email1 = "wuzhenzhao1995@gemjld.com"
email2 = "wuyucong@gemjld.com"
plain = false
[languages.en.params.contact]
enable = false
title = "contact us"
body = "please contact us"
phone1 = "136 9300 3803"
phone2 = "134 8882 8598"
address = "Plant No. 40-11, Shengda 1st branch road, wangwenzhuang Town, Xiqing District, Tianjin"
email1 = "wuzhenzhao1995@gemjld.com"
email2 = "wuyucong@gemjld.com"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

